name: Security Scan with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: sprintfloyd
          POSTGRES_PASSWORD: sprintfloyd
          POSTGRES_DB: ms3
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U sprintfloyd"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permissions to Maven Wrapper
        run: chmod +x mvnw

      - name: Build and Run the Spring Boot App
        run: |
          ./mvnw clean package -DskipTests
          java -jar target/*.jar &
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ms3
          SPRING_DATASOURCE_USERNAME: sprintfloyd
          SPRING_DATASOURCE_PASSWORD: sprintfloyd
          SERVER_PORT: 8080

      - name: Wait for Spring Boot Application to Start
        run: |
          echo "Waiting for the application to be ready..."
          timeout 60s bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 5; done'

      - name: Ensure ZAP working directory exists
        run: mkdir -p /home/runner/work/MS3-test/MS3-test/.zap && chmod -R 777 /home/runner/work/MS3-test/MS3-test/.zap

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "http://localhost:8080"
          fail_action: false  # Evita il fallimento del job se ci sono vulnerabilità
          rules_file_name: ".zap/rules.tsv"

#      - name: Run OWASP ZAP Baseline Scan
#        uses: zaproxy/action-baseline@v0.9.0
#        with:
#          target: "http://localhost:8080"
#          fail_action: false
#          cmd_options: "-J zap_report.json -w zap_report.md -r zap_report.html"

      - name: Upload OWASP ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap.out